# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-11 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField()),
                ('app_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('model_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('model_instance_pk', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_json_blob', models.TextField(blank=True, default='')),
                ('current_json_blob', models.TextField(blank=True, default='')),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LogExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=255)),
                ('field_value', models.CharField(db_index=True, max_length=255)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='loggings.Log')),
            ],
            options={
                'ordering': ['-log__timestamp'],
            },
        ),
    ]
