# Generated by Django 3.2.20 on 2024-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
