# Generated by Django 3.2.20 on 2024-02-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggings', '0002_alter_log_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.SmallIntegerField(db_index=True),
        ),
    ]
